// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: api/geoip/geoip.proto

package geoip

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGeoInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *GetGeoInfoRequest) Reset() {
	*x = GetGeoInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_geoip_geoip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGeoInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeoInfoRequest) ProtoMessage() {}

func (x *GetGeoInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_geoip_geoip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeoInfoRequest.ProtoReflect.Descriptor instead.
func (*GetGeoInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_geoip_geoip_proto_rawDescGZIP(), []int{0}
}

func (x *GetGeoInfoRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type GetGeoInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country  string                    `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Province string                    `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
	City     string                    `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Location *GetGeoInfoReply_Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Isp      string                    `protobuf:"bytes,5,opt,name=isp,proto3" json:"isp,omitempty"`
}

func (x *GetGeoInfoReply) Reset() {
	*x = GetGeoInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_geoip_geoip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGeoInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeoInfoReply) ProtoMessage() {}

func (x *GetGeoInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_geoip_geoip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeoInfoReply.ProtoReflect.Descriptor instead.
func (*GetGeoInfoReply) Descriptor() ([]byte, []int) {
	return file_api_geoip_geoip_proto_rawDescGZIP(), []int{1}
}

func (x *GetGeoInfoReply) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetGeoInfoReply) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GetGeoInfoReply) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetGeoInfoReply) GetLocation() *GetGeoInfoReply_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GetGeoInfoReply) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

type GetGeoInfoReply_Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *GetGeoInfoReply_Location) Reset() {
	*x = GetGeoInfoReply_Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_geoip_geoip_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGeoInfoReply_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeoInfoReply_Location) ProtoMessage() {}

func (x *GetGeoInfoReply_Location) ProtoReflect() protoreflect.Message {
	mi := &file_api_geoip_geoip_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeoInfoReply_Location.ProtoReflect.Descriptor instead.
func (*GetGeoInfoReply_Location) Descriptor() ([]byte, []int) {
	return file_api_geoip_geoip_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetGeoInfoReply_Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetGeoInfoReply_Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_api_geoip_geoip_proto protoreflect.FileDescriptor

var file_api_geoip_geoip_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2f, 0x67, 0x65, 0x6f, 0x69,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x65, 0x6f,
	0x69, 0x70, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0xf4, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6f,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x12, 0x3f, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x65, 0x6f, 0x69,
	0x70, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x73, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x69, 0x73, 0x70, 0x1a, 0x44, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x32, 0x5f, 0x0a, 0x05,
	0x47, 0x65, 0x6f, 0x69, 0x70, 0x12, 0x56, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6f, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e,
	0x47, 0x65, 0x74, 0x47, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0e, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x08, 0x12, 0x06, 0x2f, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x42, 0x2c, 0x0a,
	0x09, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x50, 0x01, 0x5a, 0x1d, 0x67, 0x65,
	0x6f, 0x69, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x76, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x65, 0x6f, 0x69, 0x70, 0x3b, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_geoip_geoip_proto_rawDescOnce sync.Once
	file_api_geoip_geoip_proto_rawDescData = file_api_geoip_geoip_proto_rawDesc
)

func file_api_geoip_geoip_proto_rawDescGZIP() []byte {
	file_api_geoip_geoip_proto_rawDescOnce.Do(func() {
		file_api_geoip_geoip_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_geoip_geoip_proto_rawDescData)
	})
	return file_api_geoip_geoip_proto_rawDescData
}

var file_api_geoip_geoip_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_geoip_geoip_proto_goTypes = []interface{}{
	(*GetGeoInfoRequest)(nil),        // 0: api.geoip.GetGeoInfoRequest
	(*GetGeoInfoReply)(nil),          // 1: api.geoip.GetGeoInfoReply
	(*GetGeoInfoReply_Location)(nil), // 2: api.geoip.GetGeoInfoReply.Location
}
var file_api_geoip_geoip_proto_depIdxs = []int32{
	2, // 0: api.geoip.GetGeoInfoReply.location:type_name -> api.geoip.GetGeoInfoReply.Location
	0, // 1: api.geoip.Geoip.GetGeoInfo:input_type -> api.geoip.GetGeoInfoRequest
	1, // 2: api.geoip.Geoip.GetGeoInfo:output_type -> api.geoip.GetGeoInfoReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_geoip_geoip_proto_init() }
func file_api_geoip_geoip_proto_init() {
	if File_api_geoip_geoip_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_geoip_geoip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGeoInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_geoip_geoip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGeoInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_geoip_geoip_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGeoInfoReply_Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_geoip_geoip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_geoip_geoip_proto_goTypes,
		DependencyIndexes: file_api_geoip_geoip_proto_depIdxs,
		MessageInfos:      file_api_geoip_geoip_proto_msgTypes,
	}.Build()
	File_api_geoip_geoip_proto = out.File
	file_api_geoip_geoip_proto_rawDesc = nil
	file_api_geoip_geoip_proto_goTypes = nil
	file_api_geoip_geoip_proto_depIdxs = nil
}
