// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"geoip_serivce/internal/biz"
	"geoip_serivce/internal/conf"
	"geoip_serivce/internal/data"
	"geoip_serivce/internal/server"
	"geoip_serivce/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	regionRepo := data.NewRegionRepo(dataData, logger)
	regionUsecase := biz.NewRegionUsecase(regionRepo, logger)
	locationRepo := data.NewLocationRepo(dataData, logger)
	locationUsecase := biz.NewLocationUsecase(locationRepo, logger)
	geoipService := service.NewGeoipService(regionUsecase, locationUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, geoipService, logger)
	grpcServer := server.NewGRPCServer(confServer, geoipService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
